name: Reporte de bug
description: Reportar un comportamiento no esperado.
title: "[Bug]: "
labels: ["bug"]
projects: ["clips"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomar el tiempo para reportar este bug!
  - type: textarea
    id: what-happened
    attributes:
      label: Qué pasó?
      description: Cuentanos que viste y cual es el resultado que esperabas!
      value: "..."
    validations:
      required: true
  - type: dropdown
    id: impact-level
    attributes:
      label: Nivel de Impacto
      description: Cúal es el nivel que impacto que consideras para este bug?
      options:
       - HIGH (Mejora de funcionalidad, rendimiento o seguridad que compromete la aplicación)
       - MEDIUM (Mejora que no compromete la aplicación)
       - LOW (Mejora a nivel de código que no afecta al usuario)
      default: 0
    validations:
      required: true
